/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hazelcast_jet_cpp_EntryPoint */

#ifndef _Included_com_hazelcast_jet_cpp_EntryPoint
#define _Included_com_hazelcast_jet_cpp_EntryPoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hazelcast_jet_cpp_EntryPoint
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hazelcast_jet_cpp_EntryPoint_run
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
